### ISSUE TITLE
Kartlag med ...-url'er

### ISSUE THREAD

**Issue by stigat** [Artsdatabanken/responssjekk#27]
Kartlag med "..." i URL (alle disse er 'underlag'):
- [x] 19-18  Verneplan for Vassdrag
- [x] 34-80 Hovedelv
- [x] 34-81 Elvenett
- [x] 35-82 Innsjødatabase
- [x] 35-110 Dybdekart
- [x] 35-111 Innsjo ved dybdemaling
- [x] 35-112 DybdeKurve
- [x] 35-112 DybdeKurve
- [x] 39-94 Nedbørfelt til hav
- [x] 39-95 Sidenedbørfelt
- [x] 39-96 REGINE enhet
- [x] 40-98 Dam
- [x] 40-99 Dam_N250
- [x] 40-99 Dam_N250
- [x] 40-101 Vannvei
- [x] 40-101 Vannvei
- [x] 40-102 Utløpspunkt
- [x] 40-103 Inntakspunkt
- [x] 40-104 Vannkraftverk
- [x] 59-172 Skredtype
Får man satt riktig url for disse kan vi trolig forvente mye færre røde linjer på statussiden :)

**Comment by runningbones** [comment]
oppdatert URL for alle sublayers i #27
